name: Build Android

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install NPM Modules Angular And Ionic
        run: |
          npm install -g @ionic/cli
          npm i -D -E @angular/cli
          npm install

      - name: Build Ionic App
        run: ionic build

      - name: Copy Android
        run: ionic capacitor copy android

      - name: Capacitor update
        run: npx cap update

      - name: Capacitor copy
        run: npx cap copy

      - name: Change wrapper permissions
        working-directory: ./android/
        run: chmod +x ./gradlew

      - name: Build gradle project
        working-directory: ./android/
        run: ./gradlew build

      - name: Build Android Dev APK
        if: ${{ github.ref == 'refs/heads/develop' }}
        working-directory: ./android/
        run: ./gradlew assembleDebug

      - name: Build Android Release APK
        if: ${{ github.ref == 'refs/heads/main' }}
        working-directory: ./android/
        run: ./gradlew assemble

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundle

      - name: Upload dev APK and AAD
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: actions/upload-artifact@v3
        with:
          name: app-dev
          path: |
            android/app/build/outputs/bundle/debug/app-debug.aab
            android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 14

      - name: Upload release bundle
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: |
            android/app/build/outputs/bundle/release/app-release.aab
            android/app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 14
